accent-color: "#8a0404"
google_analytics: ""
plugins:
  - jekyll-paginate
disqus: justgoodthemes
permalink: /:title
paginate_path: /page:num/
sass:
  sass_dir: _sass
  style: compressed
lang: en-US
title: Nisse & Nutmeg
description: Recipes, Recommendations, Norway, Nisse, Nutmeg & Pepper
asciicomment: |-2
         _                        
         \`*-.                    
          )  _`-.   meow!           
         .  : `. .  /             
         : _   '  \               
         ; *` _.   `*-._          
         `-.-'          `-.       
           ;       `       `.     
           :.       .        \    
           . \  .   :   .-'   .   
           '  `+.;  ;  '      :   
           :  '  |    ;       ;-. 
           ; '   : :`-:     _.`* ;
        .*' /  .*' ; .*`- +'  `*' 
        `*-*   `*-*  `*-*' 
accent_color: "#800000"
markdown: kramdown
url: https://nisseandnutmeg.netlify.app
favicon: images/favicon.png
navigation:
  - text: Home
    url: /
  - text: Norway
    url: /tags#norway
  - text: Goats
    url: /tags#goats
  - text: Books
    url: /tags#books
  - text: Recipes
    url: /recipes/
  - text: Tags
    url: /tags/
collections:
  recipes:
    output: true
    permalink: /:collection/:name
paginate: 3
footer:
  content: "&copy; Lila Wilson 2021"
  has_social: true
baseurl: ""
