accent-color: "#800000"
google_analytics: ""
plugins:
  - jekyll-paginate
disqus: justgoodthemes
permalink: /:title
paginate_path: /page:num/
sass:
  sass_dir: _sass
  style: compressed
lang: en-US
accent_color: "#800000"
markdown: kramdown
baseurl: ""
url: https://lilawilson.github.io
favicon: images/favicon.png
description: The description of the Nisse and Nutmeg site...
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Recipes
    url: /recipes/
  - text: Tags
    url: /tags/
paginate: 3
title: Nisse & Nutmeg
footer:
  content: "&copy; Lila Wilson 2021"
  has_social: true
