accent-color: "#8a0404"
google_analytics: ""
plugins:
  - jekyll-paginate
disqus: justgoodthemes
permalink: /:title
paginate_path: /page:num/
sass:
  sass_dir: _sass
  style: compressed
lang: en-US
accent_color: "#800000"
markdown: kramdown
url: https://lilawilson.github.io
favicon: images/favicon.png
description: Recipes, Recommendations, Norway, Nisse, Nutmeg & Pepper
navigation:
  - text: Home
    url: /
  - text: Norway
    url: /tags#norway
  - text: Goats
    url: /tags#goats
  - text: Books
    url: /tags#books
  - text: Recipes
    url: /recipes/
  - text: Tags
    url: /tags/
paginate: 3
title: Nisse & Nutmeg
footer:
  content: "&copy; Lila Wilson 2021"
  has_social: true
baseurl: ""
